# GitHub Actions workflow for Attendance System
name: Daily Attendance Report

on:
  schedule:
    # Run daily at 12:30 PM UTC (adjust timezone as needed)
    - cron: '30 12 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-attendance-report:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y unixodbc-dev
        # Install Microsoft ODBC Driver
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/22.04/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
        sudo apt-get update
        sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "DB_SERVER=${{ secrets.DB_SERVER }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> .env
        echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env
        echo "EMAIL_TO=${{ secrets.EMAIL_TO }}" >> .env
        echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> .env
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> .env
        echo "RUN_IMMEDIATELY=true" >> .env
    
    - name: Run attendance system
      run: |
        python attendance_system.py
    
    - name: Upload logs (if any)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: attendance-logs
        path: |
          *.log
          *.xlsx
        retention-days: 7
      if: always()
      with:
        name: attendance-logs
        path: |
          *.log
          *.xlsx
        retention-days: 7
